// app.js
// FAST VERSION (no scraping in the browser)
// - Loads ONE file: enriched_books.json (generated by your GitHub Action)
// - Main grid shows: Title, Author, ISBN, Cover, Genre
// - Description shows only when you click a book (modal)
// - Includes Search + Genre filter
// - Includes a loading overlay (no pop-in)

const DATA_URL = "enriched_books.json"; // ✅ IMPORTANT

const els = {
  search: document.getElementById("search"),
  results: document.getElementById("results"),
  status: document.getElementById("status"),
  genreFilter: document.getElementById("genreFilter"),
};

// Loading overlay elements (from index.html)
const loading = {
  overlay: document.getElementById("loadingOverlay"),
  text: document.getElementById("loadingText"),
};

function setLoading(on, msg = "") {
  if (!loading.overlay) return;
  loading.overlay.style.display = on ? "flex" : "none";
  if (loading.text && msg) loading.text.textContent = msg;
}

// Modal elements
const modal = {
  backdrop: document.getElementById("modalBackdrop"),
  closeBtn: document.getElementById("modalClose"),
  coverWrap: document.getElementById("modalCoverWrap"),
  title: document.getElementById("modalTitle"),
  author: document.getElementById("modalAuthor"),
  isbn: document.getElementById("modalIsbn"),
  genre: document.getElementById("modalGenre"),
  desc: document.getElementById("modalDesc"),
};

let ENRICHED = [];

// ---------- helpers ----------
function norm(s) {
  return (s ?? "").toString().trim();
}

function cleanIsbn(isbn) {
  return norm(isbn).replace(/[^0-9Xx]/g, "").toUpperCase();
}

function escapeHtml(s) {
  return String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

// ---------- load enriched_books.json ----------
async function loadBooks() {
  // Use default cache for speed; when you update files, hard refresh (Cmd+Shift+R)
  const res = await fetch(DATA_URL, { cache: "default" });
  if (!res.ok) throw new Error(`Failed to load ${DATA_URL} (${res.status})`);
  const data = await res.json();

  // Normalize fields (supports both {title, author, isbn} and {Title, Author, ISBN})
  return data
    .map((row, idx) => ({
      _id: row._id ?? idx,
      title: row.title ?? row.Title ?? "",
      author: row.author ?? row.Author ?? row.Auther ?? "",
      isbn: cleanIsbn(row.isbn ?? row.ISBN ?? ""),
      coverUrl: row.coverUrl ?? "",
      description: row.description ?? "",
      genre: row.genre ?? "Unknown",
      source: row.source ?? "",
    }))
    .filter((b) => b.title || b.author || b.isbn);
}

// ---------- modal ----------
function openModal(book) {
  modal.title.textContent = book.title || "Untitled";
  modal.author.textContent = `Author: ${book.author || "Unknown author"}`;
  modal.isbn.textContent = `ISBN: ${book.isbn || "—"}`;
  modal.genre.textContent = `Genre: ${book.genre || "Unknown"}`;
  modal.desc.textContent = book.description || "No description found.";

  if (book.coverUrl) {
    modal.coverWrap.innerHTML = `<img src="${escapeHtml(book.coverUrl)}" alt="Cover for ${escapeHtml(
      book.title || "Untitled"
    )}">`;
  } else {
    modal.coverWrap.innerHTML = `<div class="cover placeholder" style="width:220px;height:330px;border-radius:12px;">No cover</div>`;
  }

  modal.backdrop.classList.remove("hidden");
  modal.backdrop.setAttribute("aria-hidden", "false");
}

function closeModal() {
  modal.backdrop.classList.add("hidden");
  modal.backdrop.setAttribute("aria-hidden", "true");
}

modal.closeBtn?.addEventListener("click", closeModal);
modal.backdrop?.addEventListener("click", (e) => {
  if (e.target === modal.backdrop) closeModal();
});
document.addEventListener("keydown", (e) => {
  if (e.key === "Escape" && !modal.backdrop.classList.contains("hidden")) closeModal();
});

// ---------- filters + render ----------
function buildGenreFilter(books) {
  const genres = Array.from(new Set(books.map((b) => b.genre || "Unknown")))
    .map((g) => g || "Unknown")
    .sort((a, b) => a.localeCompare(b));

  els.genreFilter.innerHTML =
    `<option value="">All Genres</option>` +
    genres.map((g) => `<option value="${escapeHtml(g)}">${escapeHtml(g)}</option>`).join("");
}

function matchesSearch(b, q) {
  if (!q) return true;
  q = q.toLowerCase();
  return (
    (b.title || "").toLowerCase().includes(q) ||
    (b.author || "").toLowerCase().includes(q) ||
    (b.isbn || "").toLowerCase().includes(q)
  );
}

function render() {
  const q = norm(els.search?.value).toLowerCase();
  const g = els.genreFilter?.value || "";

  const filtered = ENRICHED.filter((b) => {
    const okSearch = matchesSearch(b, q);
    const okGenre = !g || b.genre === g;
    return okSearch && okGenre;
  });

  els.status.textContent = `${filtered.length} book(s)`;

  // ✅ NO DESCRIPTION ON MAIN PAGE
  els.results.innerHTML = filtered
    .map((b) => {
      const cover = b.coverUrl
        ? `<img class="cover" src="${escapeHtml(b.coverUrl)}" alt="Cover for ${escapeHtml(b.title)}" loading="lazy">`
        : `<div class="cover placeholder">No cover</div>`;

      return `
      <div class="card clickable" data-id="${b._id}" tabindex="0" role="button"
           aria-label="Open details for ${escapeHtml(b.title || "Untitled")}">
        ${cover}
        <div class="meta">
          <div class="title">${escapeHtml(b.title || "Untitled")}</div>
          <div class="author">${escapeHtml(b.author || "Unknown author")}</div>
          <div class="isbn">ISBN: ${escapeHtml(b.isbn || "—")}</div>
          <div class="genre">Genre: ${escapeHtml(b.genre || "Unknown")}</div>
        </div>
      </div>`;
    })
    .join("");

  // attach click/keyboard handlers
  els.results.querySelectorAll(".card.clickable").forEach((card) => {
    const id = Number(card.dataset.id);
    const book = ENRICHED.find((x) => x._id === id);
    if (!book) return;

    card.addEventListener("click", () => openModal(book));
    card.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        openModal(book);
      }
    });
  });
}

// ---------- init ----------
async function main() {
  setLoading(true, "Loading library…");
  els.status.textContent = "Loading…";

  ENRICHED = await loadBooks();

  buildGenreFilter(ENRICHED);

  els.search?.addEventListener("input", render);
  els.genreFilter?.addEventListener("change", render);

  els.status.textContent = `Loaded ${ENRICHED.length} books`;
  render();
  setLoading(false);
}

main().catch((err) => {
  console.error(err);
  els.status.textContent = "Error loading data. Check console.";
  setLoading(true, "Error loading data — open the console for details.");
});
